/*
 * This file is generated by hand.  It is simply an example of how a function should look based on the initial
 * rule.  This contains the flow and comments that should be generated in order to make the file readabele.
 */

/**
 * ldc x
 * ldc y
 * iadd
 * -->
 * ldc (x + y)
 */
int fold_constant_ldc_ldc_iadd(CODE **c) {
  /* int_oper[ldc] x */
  CODE *inst_1 = *c;
  int x;
  if (!is_ldc(inst_1, &x) {
    return 0;
  }

  /* int_load[ldc] y */
  CODE *inst_2 = next(inst_1);
  int y;
  if (!is_ldc(inst_2, &y)) {
    return 0;
  }

  /* iadd : hi */
  CODE *hi = next(inst_2);
  if (!is_iadd(hi)) {
    return 0;
  }

  /* switch (hi)
   *   iadd:
   *     ldc (x + y)
   */
  CODE *statement_1 = makeCODEldc(x + y);

  return replace(c, 3);
}
